/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ETHRegistrarController } from "./ETHRegistrarController";

export { ETHRegistrarController__factory } from "./factories/ETHRegistrarController__factory";
